import type { ShipType, GamePhase, PlacedShip } from './game'

// === Game Messages (forwarded by relay) ===

export interface ReadyMessage {
  type: 'ready'
}

export interface CommitMessage {
  type: 'commit'
  hash: string
}

export interface ShotMessage {
  type: 'shot'
  x: number
  y: number
}

export interface ResultMessage {
  type: 'result'
  x: number
  y: number
  hit: boolean
  sunk: ShipType | null
}

export interface RevealMessage {
  type: 'reveal'
  ships: PlacedShip[]
  salt: string
}

export interface RematchMessage {
  type: 'rematch'
}

export interface PingMessage {
  type: 'ping'
  timestamp: number
}

export interface PongMessage {
  type: 'pong'
  timestamp: number
}

export interface SyncRequestMessage {
  type: 'sync_request'
}

export interface SyncResponseMessage {
  type: 'sync_response'
  phase: GamePhase
  turnNumber: number
  shotHistory: Array<{
    x: number
    y: number
    hit: boolean
    sunk: ShipType | null
    player: 'a' | 'b'
  }>
}

export type GameMessage =
  | ReadyMessage
  | CommitMessage
  | ShotMessage
  | ResultMessage
  | RevealMessage
  | RematchMessage
  | PingMessage
  | PongMessage
  | SyncRequestMessage
  | SyncResponseMessage

// === Relay System Messages (generated by relay, not forwarded) ===

export interface PeerCountMessage {
  type: 'peer_count'
  count: number
}

export interface PeerLeftMessage {
  type: 'peer_left'
}

export interface RelayErrorMessage {
  type: 'error'
  code: 'ROOM_FULL' | 'INVALID_MESSAGE' | 'RATE_LIMITED'
  message: string
}

export type RelayMessage =
  | PeerCountMessage
  | PeerLeftMessage
  | RelayErrorMessage

export type IncomingMessage = GameMessage | RelayMessage

// === Client → Relay Control Messages ===

export interface JoinMessage {
  type: 'join'
  roomId: string
}

export type ClientControlMessage = JoinMessage
